name: build_test_docker
      
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP Dependency Check
        continue-on-error: true
        run: |
          echo $(pwd)
          ./run_check
      - name: Post Checks
        run: |
          ls -la
